### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by Kinostrome** [lexiconhq/lexicon#14]
This is a major feature that touches all aspects of the Lexicon Stack and involves creating a Discourse plugin to support it.

The notifications will be delivered by an integration between the Discourse plugin and the Expo Push Notifications API.

**Comment by bonsaibauer** [comment]
This is an important feature, and one of the reasons why I chose to use the Lexicon application as an app is because it will eventually provide the ability to receive push notifications. This would further enhance the entire project, as the Discourse HUB IOS/Android version only has in-app notifications.

For my community and in general, having push notifications is necessary, as I have studied group and community structures extensively. This feature, like other apps, will greatly enhance the Discourse, as updates will be instantly notified, allowing people to react more promptly to each other.

**Comment by Kinostrome** [comment]
Thanks for the input, we fully agree. Stable support for Push Notifications will be coming with our version 2 release.

(_Note that there was a bit of a "dead zone" of no development for an extended period of time after launching version 1. So while it has been quite a while since version 1 was launched, development on features like this one has happened more recently._)

Naturally, push notification support will involve installing the Discourse plugin we have been developing. This is because the source of events that generate push notifications is literally your Discourse instance.

As mentioned elsewhere, we're looking to put out a version 2 alpha branch ahead of the full release, so ideally, anyone interested will be able to interact with it sooner.

**Comment by bonsaibauer** [comment]
Here are some pieces of information I found about it, which I assume you might have already thought of 😂

- https://github.com/OneSignal/onesignal-expo-plugin
- https://github.com/pmusaraj/discourse-onesignal
