### ISSUE TITLE
Migrate to Hermes

### ISSUE THREAD

**Issue by Kinostrome** [lexiconhq/lexicon#29]
Migrate to the Hermes JS engine for the entire project.

**Comment by SimonBiggs** [comment]
Hi @Kinostrome,

I'd be quite keen to be able to help with the process of being able to have a stable release of the new updates to Lexicon. What is something that I could do to help you? I'd be open to helping with documentation, testing, bug swatting. Just keen to get the current updated work into a state where it is fit for deployment.

Cheers,
Simon

**Comment by starjustice** [comment]
> Hi @Kinostrome,
> 
> I'd be quite keen to be able to help with the process of being able to have a stable release of the new updates to Lexicon. What is something that I could do to help you? I'd be open to helping with documentation, testing, bug swatting. Just keen to get the current updated work into a state where it is fit for deployment.
> 
> Cheers, Simon

Hey Simon, thanks for your interest in this—we're really glad to have you on here wanting to help out.

At the moment we're undergoing a bit of a transition. Lexicon v2 is under development internally (with features like push notifications and email deep linking), and development on that is being synced to alpha-v2. We are gearing up to a beta launch of v2, after which we'd like to transition the project to fully open-source.

In the meantime, the master branch still contains the v1 legacy code, and these two branches are not compatible—they can't be merged into one another. Given that v2 is a major version break, this probably makes sense.

One way that you could help out quite a bit is by getting the master branch stable again with any issues that you're encountering. It should be somewhat up-to-date, but we'd be happy to review PRs that are fixing the issues you're encountering. The key point is that we can't merge PRs syncing all changes between alpha-v2 and master. These two branches have to diverge from one another since v2 will contain features that v1 did not support.

We also wrote about this on a recent post in our discussions tab, you can read about it here: https://github.com/lexiconhq/lexicon/discussions/37

**Comment by SimonBiggs** [comment]
> We are gearing up to a beta launch of v2, after which we'd like to transition the project to fully open-source.

Cheers, thanks for the update. I'll avoid touching things until such a time as the development workflow is fully open source. Once that transition is made, I'd be more than happy to help.
